# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: Data Interoperability Toolkit
    folder: /path/to/source

##### Resource List Builder Implementations #####

# A dynamic builder that creates inventories at request time
resource_list_builder:
    uri_path: resourcelist.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
changememory:
    uri_path: changelist.xml
    max_changes: 1000